name = "epusdt-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
APP_NAME = "epusdt-workers"
APP_URI = "https://epusdt.localhost"
APP_DEBUG = "true"
API_AUTH_TOKEN = "xxxxxxxxxx"
TG_BOT_TOKEN = "0000000:xxxxxxxxxxxxxxxx"
TG_MANAGE = "xxxxxxxx"
ORDER_EXPIRATION_TIME = "1440"

[[d1_databases]]
binding = "DB"
database_name = "epusdt-workers"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"

[triggers]
crons = ["* * * * *"]
